### ISSUE TITLE
Computing Infrastructure enhancements

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/imSim#21]
- [x] Enable the package to build and run on [OS X El Capitan](http://dmtn-001.lsst.io/en/master/). #18 
- [x] Connect repo to CI systems. #20
- [x] Add command/configuration file capability. #11
